POST http://127.0.0.1:8000/api/v1/pets
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json


{
  "data": {
    "type": "pet",
    "id": "592521e9-550f-4295-821f-a14e1be8b178"
  }
}
